config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'pages/home',    to: 'pages#home'
  get 'pages/about',   to: 'pages#about'
  get 'pages/contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand me-5" href="/">Dynamic Partials</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse ms-5" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= root_path %>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= pages_home_path %>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= pages_about_path %>">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= pages_contact_path %>">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dynamic Partials</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/nav' %>
    </header>

    <main class="container my-5 pb-5">
      <div class="row">
        <div class="col-3">
          <% if content_for?(:home_sidebar) %>
            <%= yield :home_sidebar %>
          <% elsif :contact_sidebar %>
            <%= yield :contact_sidebar %>
          <% else %>
            <%= render partial: 'shared/sidebar' %>
          <% end %>
        </div>
        <div class="col-9">
          <%= yield %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :about_sidebar do %>
  <%= render partial: 'shared/about_sidebar' %>
<% end %>
<h1 class="display-1 text-success">
  About
</h1>

app/views/pages/contact.html.erb
<% content_for :contact_sidebar do %>
  <%= render partial: 'shared/contact_sidebar' %>
<% end %>
<h1 class="display-1 text-success">
  Contact
</h1>

app/views/pages/home.html.erb
<% content_for :home_sidebar do %>
  <%= render partial: 'shared/home_sidebar' %>
<% end %>
<h1 class="display-1 text-success">
  Home
</h1>

app/views/shared/_about_sidebar.html.erb
<h1 class="display-1 text-success">
  About
</h1>

app/views/shared/_contact_sidebar.html.erb
<h1 class="display-1 text-success">
  Contact
</h1>

app/views/shared/_home_sidebar.html.erb
<h1 class="display-1 text-success">
  Home
</h1>

app/views/shared/_sidebar.html.erb
<div class="sidebar shadow rounded p-4 mx-5">
  <p class="display-6 text-muted">
    Sidebar
  </p>
  <ul>
    <h3 class="text-muted">
      <%= link_to 'Home', root_path %>
    </h3>
    <li>More</li>
    <li>Words</li>
    <li>Here</li>
  </ul>
</div>